### ISSUE TITLE
I got a lot of errors concerning the gonum libraries.

### ISSUE THREAD

**Issue by ypxie** [fumin/ntm#1]
../../gonum/blas/native/internal/math32/sqrt_amd64.s:17: Error: no such instruction: `text ·Sqrt(SB),NOSPLIT,$0'
../../gonum/blas/native/internal/math32/sqrt_amd64.s:18: Error: junk`(FP)' after expression
../../gonum/blas/native/internal/math32/sqrt_amd64.s:18: Error: too many memory references for `sqrtss'
../../gonum/blas/native/internal/math32/sqrt_amd64.s:19: Error: too many memory references for`movss'
# github.com/gonum/internal/asm

../../gonum/internal/asm/daxpy_amd64.s: Assembler messages:
../../gonum/internal/asm/daxpy_amd64.s:47: Error: no such instruction: `text ·DaxpyUnitary(SB),NOSPLIT,$0'
../../gonum/internal/asm/daxpy_amd64.s:48: Error: junk`(FP)' after expression
../../gonum/internal/asm/daxpy_amd64.s:48: Error: too many memory references for `movhpd'
../../gonum/internal/asm/daxpy_amd64.s:49: Error: junk`(FP)' after expression
../../gonum/internal/asm/daxpy_amd64.s:49: Error: too many memory references for `movlpd'
../../gonum/internal/asm/daxpy_amd64.s:50: Error: junk`(FP)' after expression
../../gonum/internal/asm/daxpy_amd64.s:50: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:51: Error: junk `(FP)' after expression
../../gonum/internal/asm/daxpy_amd64.s:51: Error: too many memory references for`movq'
../../gonum/internal/asm/daxpy_amd64.s:52: Error: junk `(FP)' after expression
../../gonum/internal/asm/daxpy_amd64.s:52: Error: too many memory references for`movq'
../../gonum/internal/asm/daxpy_amd64.s:53: Error: junk `(FP)' after expression
../../gonum/internal/asm/daxpy_amd64.s:53: Error: too many memory references for`movq'
../../gonum/internal/asm/daxpy_amd64.s:55: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:56: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:57: Error: bad expression
../../gonum/internal/asm/daxpy_amd64.s:57: Error: junk `if n<0 goto V1' after expression
../../gonum/internal/asm/daxpy_amd64.s:61: Error: junk`(R8)(SI_8)' after expression
../../gonum/internal/asm/daxpy_amd64.s:61: Error: too many memory references for `movupd'
../../gonum/internal/asm/daxpy_amd64.s:62: Error: junk`(R9)(SI_8)' after expression
../../gonum/internal/asm/daxpy_amd64.s:62: Error: too many memory references for `movupd'
../../gonum/internal/asm/daxpy_amd64.s:63: Error: too many memory references for`mulpd'
../../gonum/internal/asm/daxpy_amd64.s:64: Error: too many memory references for `addpd'
../../gonum/internal/asm/daxpy_amd64.s:65: Error: too many memory references for`movupd'
../../gonum/internal/asm/daxpy_amd64.s:67: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:68: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:69: Error: invalid character '=' in operand 1
../../gonum/internal/asm/daxpy_amd64.s:72: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:73: Error: invalid character '=' in operand 1
../../gonum/internal/asm/daxpy_amd64.s:76: Error: junk `(R8)(SI*8)' after expression
../../gonum/internal/asm/daxpy_amd64.s:76: Warning:`X0' is not valid here (expected `(%rbx)')
../../gonum/internal/asm/daxpy_amd64.s:77: Error: junk`(R9)(SI_8)' after expression
../../gonum/internal/asm/daxpy_amd64.s:77: Warning: `X1' is not valid here (expected`(%rbx)')
../../gonum/internal/asm/daxpy_amd64.s:78: Error: too many memory references for `mulsd'
../../gonum/internal/asm/daxpy_amd64.s:79: Error: too many memory references for`addsd'
../../gonum/internal/asm/daxpy_amd64.s:80: Error: junk `(R10)(SI_8)' after expression
../../gonum/internal/asm/daxpy_amd64.s:80: Warning: `0(R10)(SI*8)' is not valid here (expected`(%rbx)')
../../gonum/internal/asm/daxpy_amd64.s:87: Error: no such instruction: `text ·DaxpyInc(SB),NOSPLIT,$0'
../../gonum/internal/asm/daxpy_amd64.s:88: Error: junk`(FP)' after expression
../../gonum/internal/asm/daxpy_amd64.s:88: Error: too many memory references for `movhpd'
../../gonum/internal/asm/daxpy_amd64.s:89: Error: junk`(FP)' after expression
../../gonum/internal/asm/daxpy_amd64.s:89: Error: too many memory references for `movlpd'
../../gonum/internal/asm/daxpy_amd64.s:90: Error: junk`(FP)' after expression
../../gonum/internal/asm/daxpy_amd64.s:90: Error: too many memory references for `movq'
../../gonum/internal/asm/daxpy_amd64.s:91: Error: junk`(FP)' after expression
../../gonum/internal/asm/daxpy_amd64.s:91: Error: too many memory references for `movq'
../../gonum/internal/asm/daxpy_amd64.s:92: Error: junk`(FP)' after expression
../../gonum/internal/asm/daxpy_amd64.s:92: Error: too many memory references for `movq'
../../gonum/internal/asm/daxpy_amd64.s:93: Error: junk`(FP)' after expression
../../gonum/internal/asm/daxpy_amd64.s:93: Error: too many memory references for `movq'
../../gonum/internal/asm/daxpy_amd64.s:94: Error: junk`(FP)' after expression
../../gonum/internal/asm/daxpy_amd64.s:94: Error: too many memory references for `movq'
../../gonum/internal/asm/daxpy_amd64.s:95: Error: junk`(FP)' after expression
../../gonum/internal/asm/daxpy_amd64.s:95: Error: too many memory references for `movq'
../../gonum/internal/asm/daxpy_amd64.s:96: Error: junk`(FP)' after expression
../../gonum/internal/asm/daxpy_amd64.s:96: Error: too many memory references for `movq'
../../gonum/internal/asm/daxpy_amd64.s:98: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:99: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:100: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:101: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:102: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:103: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:105: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:106: Error: bad expression
../../gonum/internal/asm/daxpy_amd64.s:106: Error: junk`if n<0 goto V2' after expression
../../gonum/internal/asm/daxpy_amd64.s:110: Error: junk `(R8)(SI*8)' after expression
../../gonum/internal/asm/daxpy_amd64.s:110: Error: too many memory references for`movhpd'
../../gonum/internal/asm/daxpy_amd64.s:111: Error: junk `(R9)(DI*8)' after expression
../../gonum/internal/asm/daxpy_amd64.s:111: Error: too many memory references for`movhpd'
../../gonum/internal/asm/daxpy_amd64.s:112: Error: junk `(R8)(AX*8)' after expression
../../gonum/internal/asm/daxpy_amd64.s:112: Error: too many memory references for`movlpd'
../../gonum/internal/asm/daxpy_amd64.s:113: Error: junk `(R9)(BX*8)' after expression
../../gonum/internal/asm/daxpy_amd64.s:113: Error: too many memory references for`movlpd'
../../gonum/internal/asm/daxpy_amd64.s:115: Error: too many memory references for `mulpd'
../../gonum/internal/asm/daxpy_amd64.s:116: Error: too many memory references for`addpd'
../../gonum/internal/asm/daxpy_amd64.s:117: Error: too many memory references for `movhpd'
../../gonum/internal/asm/daxpy_amd64.s:118: Error: too many memory references for`movlpd'
../../gonum/internal/asm/daxpy_amd64.s:120: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:121: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:122: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:123: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:125: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:126: Error: invalid character '=' in operand 1
../../gonum/internal/asm/daxpy_amd64.s:129: Error: invalid character '=' in operand 2
../../gonum/internal/asm/daxpy_amd64.s:130: Error: invalid character '=' in operand 1
../../gonum/internal/asm/daxpy_amd64.s:133: Error: junk `(R8)(SI*8)' after expression
../../gonum/internal/asm/daxpy_amd64.s:133: Warning:`X0' is not valid here (expected `(%rbx)')
../../gonum/internal/asm/daxpy_amd64.s:134: Error: junk`(R9)(DI_8)' after expression
../../gonum/internal/asm/daxpy_amd64.s:134: Warning: `X1' is not valid here (expected`(%rbx)')
../../gonum/internal/asm/daxpy_amd64.s:135: Error: too many memory references for `mulsd'
../../gonum/internal/asm/daxpy_amd64.s:136: Error: too many memory references for`addsd'
../../gonum/internal/asm/daxpy_amd64.s:137: Error: junk `(R9)(DI_8)' after expression
../../gonum/internal/asm/daxpy_amd64.s:137: Warning: `0(R9)(DI*8)' is not valid here (expected`(%rbx)')

**Comment by fumin** [comment]
Hi shampool

This is due to the fact that gonum/blas is not installed on your machine yet.
The quick fix is to run the pure Go version by checking out to the pure-go tag as in `git checkout pure-go`, or if you like download the source from https://github.com/fumin/ntm/releases/tag/pure-go . From there on, you are good to go to replicate the results in the paper.
Alternatively, you could install gonum/blas by following the steps in https://github.com/gonum/blas.
