### ISSUE TITLE
Duplicate Detection

### ISSUE THREAD

**Issue by qingyuanxingsi** [fumin/ntm#3]
In sub-task **Acrostic generation**, section(https://github.com/fumin/ntm/blob/master/poem/test/main.go#L106) you force the characters in a generated poem(**TEST PHASE**) to be different from each other, is this assumption reasonable??As far as I know, there are many poems with same characters. Or are there other considerations?

**Comment by fumin** [comment]
Hi Qing

Good question, forcing the characters to be different is obviously a kludge and I am also aware that there are many poems with the same characters appearing more than once. However, I also observed that the current trained network is too obsessed with the most popular characters such as 山，水，天, to the extent that they might appear more than three or four times, which I subjectively think is excessive. Therefore, I think it definitely is a weakness and perhaps an area for further research and improvement, but it is the best I have for now in terms of generating poems as the end product. It would be great if you have ideas to eliminate it!
